### ISSUE TITLE
Inconsistent behavior of job/status metric.

### ISSUE THREAD

**Issue by sharkinsspatial** [pangeo-forge/dataflow-status-monitoring#1]
This repo is my initial attempt at a Dataflow status monitoring and reporting approach as outlined in https://github.com/pangeo-forge/registrar/issues/47.  There does not seem to be a consistently documented approach for providing external notifications of Dataflow job success or failure (most approaches describe using log sinks to identify and report failed jobs but don't provide a recommended strategy for successful jobs).

While the approach of Cloud Monitoring Alerts that I've taken here appears to work, I've noticed that `job/status` [metric](https://cloud.google.com/monitoring/api/metrics_gcp#gcp-dataflow) occasionally seems to not report successful jobs.  This is my first time working with Cloud Monitoring and [MQL](https://cloud.google.com/monitoring/mql/reference) so I'm unsure if this is related to an error in my [table alignment logic](https://github.com/pangeo-forge/dataflow-status-monitoring/blob/60e1d9c8acb40ed9d7b59b57e202e999dbfc308c/terraform/alert_policy.tf#L15) or if this is an issue with my understanding of the metric itself.

@alxmrs If you have a moment, can you provide some feedback on if my approach is usable or if there is a recommended approach for monitoring Dataflow jobs and reporting their status to external applications (via a webhook).  cc @cisaacstern

**Comment by sharkinsspatial** [comment]
I'm curious if this might somehow be related to this note which is included in the `job/status` metric docs `Not reported while the pipeline is not running`?  This appears to be the only metric I see with this caveat.

**Comment by alxmrs** [comment]
I've discussed this with some engineers internally who are more familiar with GCP (Thanks, @Cidan). Here are a few thoughts: 
- One thing that could be going on is there is a race: The job finishes before the metric is reported. One possible workaround for this is to drop the alignment. This way, we can see if it's an alignment issue, even if it triggers false alerts. 
- A possible tactic here could involve querying the [Dataflow REST API](https://cloud.google.com/dataflow/docs/reference/rest). However, this would favor a polling approach instead of something event driven, which is definitely a better fit here.
